### ISSUE TITLE
same name with factory method

### ISSUE THREAD

**Issue by devnieL** [TooTallNate/node-function-name#3] opened 2015-03-08 20:07 UTC
Hi,

I'm using a factory method that should return a function with different names for each call. Do you know why this mocha test case doesn't run as expected ?

```
var set = require('function-name');
var assert = require('assert');

describe('function-name', function () {
	
	it(" should set different names on factory", function(done){

		var f1 = null;
		var f2 = null;

		var factory = function(){
			var Y = function test(){};
			set(Y, Math.random());
			return Y;	
		}

		f1 = factory();
		f2 = factory();

		assert.notEqual(f1.name, f2.name);
		done();
	});

});

// Result : AssertionError: "0.743471089284867" != "0.743471089284867"
```

It works fine with [Function.create](https://github.com/walling/Function.create.js) but I'm not sure if it's enough secure as node-function-name. Any comment will be appreciated.

Thanks!

**Comment by greenboxal** [comment] 2015-04-27 05:38
This is caused by a what we could call a "bug" in V8 function cache.

`Function.prototype.name` is defined as follow(simplified):
```
v8::String v8::Function::GetName() {
    return reinterpret_cast<i::JSFunction>(Utils::OpenHandle(this))->shared()->name();
}
```

When multiple functions with the same body are found, they share the same structure in V8 heap. The problem is that the function name is within that structure(`SharedFunctionInfo`) and not with the `JSFunction` itself.

Basically, when you change one function name you end up changing all functions that shares the same code name.

I could assume that this is a won't fix until Harmony function name draft is implemented(http://wiki.ecmascript.org/doku.php?id=harmony:function_name_property).

**Comment by TooTallNate** [comment] 2015-12-02 00:48
I ended up figuring out a pretty nasty workaround for this:

``` js
var crypto = require('crypto');
var assert = require('assert');
var set = require('function-name');

function c (p) {
  var name;
  do {
    name = crypto.randomBytes(100).toString('hex');
  } while (/\d/.test(name[0]));

  return new Function('p',
    'return function ' + name + '(){' +
      'return p.apply(this,arguments);' +
    '};')(p);
}

var f1 = null;
var f2 = null;

var factory = function(){
  var Y = c(function test(){});
  set(Y, Math.random());
  return Y;
}

f1 = factory();
f2 = factory();

assert.notEqual(f1.name, f2.name);
```

The trick is that we have to generate a proxy function with a unique named function. I'm using `crypto.randomBytes(100).toString('hex')` here to create a _"unique"_ name, but there are better ways of doing this.

Again, this is extremely nasty, and doesn't really make a lot of sense. But it works if you're in a pinch and _really, really __NEED___ to create `name` properties that otherwise would be syntax errors. Otherwise `Function.create()` _almost_ does the job perfectly.

**Comment by TooTallNate** [comment] 2015-12-31 05:56
For the record, I created a module that wraps up this logic as well as custom arity logic, invoke logic and inheritance (basically everything you need to create useful Function subclasses) in this module: [`function-class`](https://github.com/TooTallNate/node-function-class).

Closing!

**Closed by TooTallNate** 2015-12-31 05:56 UTC
